//! zero-loadtest — drives many concurrent WebSocket clients against a
//! zero-cache server and reports latency / throughput / resource usage. Can run
//! against two targets (`--compare`) for a head-to-head vs `rocicorp/zero`.
//!
//! Usage (env or flags; flags win):
//!   --url ws://127.0.0.1:4848/sync   (LOAD_URL)      target server
//!   --clients 1000                   (LOAD_CLIENTS)  concurrent clients
//!   --duration 20                    (LOAD_DURATION) seconds of sustained load
//!   --ramp 5                         (LOAD_RAMP)     seconds to stagger connects
//!   --setup-timeout 120              (LOAD_SETUP_TIMEOUT) seconds per setup phase
//!   --ping-interval 250              (LOAD_PING_MS)  ms between pings per client
//!   --burst                          all clients connect at once (thundering herd)
//!   --workload hydrate                (LOAD_WORKLOAD) ping|hydrate|fanout|reconnect
//!   --fanout-min-pokes 1              (LOAD_FANOUT_MIN_POKES) require live pokes
//!   --container zero-cache           (LOAD_CONTAINER) docker container for `docker stats`
//!   --compare --ref-url ws://…:4849/sync --ref-container zero-ref
//!
//! Note: at high client counts raise the fd limit (`ulimit -n 100000`).

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use futures_util::{SinkExt, StreamExt};
use tokio_tungstenite::tungstenite::client::IntoClientRequest;
use tokio_tungstenite::tungstenite::Message;

use zero_loadtest::{render_report, resource_stats, ResourceStats, RunReport};

struct Config {
    url: String,
    clients: usize,
    duration: Duration,
    ramp: Duration,
    setup_timeout: Duration,
    ping_interval: Duration,
    burst: bool,
    workload: Workload,
    desired_query_patch: String,
    client_schema: String,
    fanout_min_pokes: u64,
    container: Option<String>,
    compare: bool,
    ref_url: Option<String>,
    ref_container: Option<String>,
}

/// The traffic shape driven after the WebSocket handshake. `ping` retains the
/// original control-plane benchmark; the other modes exercise actual Zero
/// state transitions and therefore need the seeded `issue` schema by default.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum Workload {
    Ping,
    Hydrate,
    /// Hydrate first, then observe post-hydration pokes generated by an
    /// external writer. `--fanout-min-pokes` makes that observation a gate.
    Fanout,
    Reconnect,
}

impl Workload {
    fn parse(value: &str) -> Result<Self, String> {
        match value {
            "ping" => Ok(Self::Ping),
            "hydrate" => Ok(Self::Hydrate),
            "fanout" => Ok(Self::Fanout),
            "reconnect" => Ok(Self::Reconnect),
            _ => Err(format!(
                "invalid workload {value:?}; expected ping, hydrate, fanout, or reconnect"
            )),
        }
    }

    fn needs_hydration(self) -> bool {
        !matches!(self, Self::Ping)
    }

    fn name(self) -> &'static str {
        match self {
            Self::Ping => "ping",
            Self::Hydrate => "hydrate",
            Self::Fanout => "fanout",
            Self::Reconnect => "reconnect",
        }
    }
}

/// The benchmark stack's deterministic query and client schema. Both are
/// configurable for a different app (`--query-patch` / `--client-schema`), but
/// retaining a nonempty default prevents a data-path benchmark accidentally
/// falling back to an empty desired-query patch.
const DEFAULT_QUERY_PATCH: &str =
    r#"[{"op":"put","hash":"loadtest-issue-all","ast":{"table":"issue"}}]"#;
const DEFAULT_CLIENT_SCHEMA: &str = r#"{"tables":{"issue":{"columns":{"id":{"type":"string"},"title":{"type":"string"},"owner":{"type":"string"},"open":{"type":"boolean"},"rank":{"type":"number"}},"primaryKey":["id"]}}}"#;

fn env_or(flag_val: Option<String>, env: &str, default: &str) -> String {
    flag_val
        .or_else(|| std::env::var(env).ok())
        .unwrap_or_else(|| default.to_string())
}

fn parse_config() -> Config {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let flag = |name: &str| -> Option<String> {
        args.iter()
            .position(|a| a == name)
            .and_then(|i| args.get(i + 1).cloned())
    };
    let has = |name: &str| args.iter().any(|a| a == name);

    let workload_text = env_or(flag("--workload"), "LOAD_WORKLOAD", "ping");
    let workload = Workload::parse(&workload_text).unwrap_or_else(|error| {
        eprintln!("zero-loadtest: {error}");
        std::process::exit(2);
    });
    let desired_query_patch = env_or(
        flag("--query-patch"),
        "LOAD_QUERY_PATCH",
        DEFAULT_QUERY_PATCH,
    );
    let client_schema = env_or(
        flag("--client-schema"),
        "LOAD_CLIENT_SCHEMA",
        DEFAULT_CLIENT_SCHEMA,
    );
    for (label, json) in [
        ("query patch", desired_query_patch.as_str()),
        ("client schema", client_schema.as_str()),
    ] {
        if serde_json::from_str::<serde_json::Value>(json).is_err() {
            eprintln!("zero-loadtest: {label} is not valid JSON");
            std::process::exit(2);
        }
    }

    Config {
        url: env_or(flag("--url"), "LOAD_URL", "ws://127.0.0.1:4848/sync"),
        clients: env_or(flag("--clients"), "LOAD_CLIENTS", "1000")
            .parse()
            .unwrap_or(1000),
        duration: Duration::from_secs(
            env_or(flag("--duration"), "LOAD_DURATION", "20")
                .parse()
                .unwrap_or(20),
        ),
        ramp: Duration::from_secs(
            env_or(flag("--ramp"), "LOAD_RAMP", "5")
                .parse()
                .unwrap_or(5),
        ),
        setup_timeout: Duration::from_secs(
            env_or(flag("--setup-timeout"), "LOAD_SETUP_TIMEOUT", "120")
                .parse()
                .unwrap_or(120),
        ),
        ping_interval: Duration::from_millis(
            env_or(flag("--ping-interval"), "LOAD_PING_MS", "250")
                .parse()
                .unwrap_or(250),
        ),
        burst: has("--burst"),
        workload,
        desired_query_patch,
        client_schema,
        fanout_min_pokes: env_or(flag("--fanout-min-pokes"), "LOAD_FANOUT_MIN_POKES", "0")
            .parse()
            .unwrap_or_else(|_| {
                eprintln!("zero-loadtest: --fanout-min-pokes must be a non-negative integer");
                std::process::exit(2);
            }),
        container: flag("--container").or_else(|| std::env::var("LOAD_CONTAINER").ok()),
        compare: has("--compare"),
        ref_url: flag("--ref-url").or_else(|| std::env::var("LOAD_REF_URL").ok()),
        ref_container: flag("--ref-container").or_else(|| std::env::var("LOAD_REF_CONTAINER").ok()),
    }
}

/// One client's session outcome.
#[derive(Default)]
struct ClientResult {
    connected: bool,
    connect_ms: f64,
    ping_rtts: Vec<f64>,
    hydrated: bool,
    hydration_ms: Option<f64>,
    reconnected: bool,
    reconnect_ms: Option<f64>,
    fanout_pokes: u64,
    frames: u64,
    error: Option<String>,
}

/// The zero sync protocol version this harness speaks (matches
/// `@rocicorp/zero`'s `PROTOCOL_VERSION`). The real connect path is
/// `/sync/v{PROTOCOL_VERSION}/connect`.
const PROTOCOL_VERSION: u32 = 51;

/// Normalizes a target into a base origin (`ws://host:port`), stripping a
/// trailing `/sync`, `/sync/vN/connect`, or `/`.
fn base_origin(url: &str) -> String {
    let u = url.trim_end_matches('/');
    if let Some(idx) = u.find("/sync") {
        u[..idx].to_string()
    } else {
        u.to_string()
    }
}

/// Builds the real `@rocicorp/zero` connect URL. Each benchmark client gets a
/// distinct client group, while reconnect mode deliberately reuses its group
/// and client ID with the cookie produced by the first connection.
fn connect_url(
    base: &str,
    client_group_id: &str,
    client_id: &str,
    wsid: &str,
    base_cookie: Option<&str>,
) -> String {
    format!(
        "{base}/sync/v{PROTOCOL_VERSION}/connect\
         ?clientGroupID={}&clientID={}&wsid={}&schemaVersion=1&baseCookie={}&ts=0&lmid=0",
        query_component(client_group_id),
        query_component(client_id),
        query_component(wsid),
        query_component(base_cookie.unwrap_or("")),
    )
}

fn query_component(value: &str) -> String {
    let mut encoded = String::with_capacity(value.len());
    for byte in value.bytes() {
        if byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.' | b'~') {
            encoded.push(char::from(byte));
        } else {
            encoded.push_str(&format!("%{byte:02X}"));
        }
    }
    encoded
}

/// The `Sec-WebSocket-Protocol` value an official Zero client sends with no
/// initial message and no auth. JavaScript's `JSON.stringify` omits both
/// `undefined` fields, so the encoded payload is `{}` (not explicit `null`
/// fields). Official zero-cache distinguishes those shapes during handshake.
fn sec_protocol_no_auth() -> String {
    use base64::Engine;
    let payload = "{}";
    let b64 = base64::engine::general_purpose::STANDARD.encode(payload.as_bytes());
    // encodeURIComponent escapes base64's +, /, = (the only non-alphanumerics).
    b64.replace('+', "%2B")
        .replace('/', "%2F")
        .replace('=', "%3D")
}

type WebSocket =
    tokio_tungstenite::WebSocketStream<tokio_tungstenite::MaybeTlsStream<tokio::net::TcpStream>>;
type WebSocketSink = futures_util::stream::SplitSink<WebSocket, Message>;
type WebSocketStream = futures_util::stream::SplitStream<WebSocket>;

async fn dial(
    base: &str,
    client_group_id: &str,
    client_id: &str,
    wsid: &str,
    base_cookie: Option<&str>,
    setup_timeout: Duration,
) -> Result<(WebSocket, f64), String> {
    let url = connect_url(base, client_group_id, client_id, wsid, base_cookie);
    let mut req = url
        .into_client_request()
        .map_err(|error| format!("bad url: {error}"))?;
    // Real zero requires the Sec-WebSocket-Protocol handshake header.
    let protocol = sec_protocol_no_auth()
        .parse()
        .map_err(|error| format!("bad Sec-WebSocket-Protocol header: {error}"))?;
    req.headers_mut().insert("Sec-WebSocket-Protocol", protocol);

    let started = Instant::now();
    let ws = tokio::time::timeout(setup_timeout, tokio_tungstenite::connect_async(req))
        .await
        .map_err(|_| "connect timeout".to_string())?
        .map_err(|error| format!("connect: {}", classify(&error.to_string())))?
        .0;
    Ok((ws, started.elapsed().as_secs_f64() * 1000.0))
}

async fn consume_greeting(
    stream: &mut WebSocketStream,
    result: &mut ClientResult,
    setup_timeout: Duration,
) -> Result<(), String> {
    match tokio::time::timeout(setup_timeout, stream.next()).await {
        Ok(Some(Ok(Message::Text(text)))) if text.starts_with("[\"connected\"") => {
            result.frames += 1;
            Ok(())
        }
        Ok(Some(Ok(Message::Close(_)))) | Ok(None) => Err("closed before greeting".into()),
        Ok(Some(Ok(_))) => Err("non-text greeting".into()),
        Ok(Some(Err(error))) => Err(format!(
            "greeting receive: {}",
            classify(&error.to_string())
        )),
        Err(_) => Err("greeting timeout".into()),
    }
}

fn init_message(desired_queries_patch: &str, client_schema: Option<&str>) -> String {
    match client_schema {
        Some(schema) => format!(
            r#"["initConnection",{{"desiredQueriesPatch":{desired_queries_patch},"clientSchema":{schema}}}]"#
        ),
        None => format!(r#"["initConnection",{{"desiredQueriesPatch":{desired_queries_patch}}}]"#),
    }
}

fn text_tag(text: &str) -> Option<String> {
    serde_json::from_str::<serde_json::Value>(text)
        .ok()
        .and_then(|value| {
            value
                .as_array()
                .and_then(|parts| parts.first())
                .and_then(serde_json::Value::as_str)
                .map(str::to_owned)
        })
}

fn poke_end_cookie(text: &str) -> Option<String> {
    let value: serde_json::Value = serde_json::from_str(text).ok()?;
    if value.as_array()?.first()?.as_str()? == "pokeEnd" {
        value.get(1)?.get("cookie")?.as_str().map(str::to_owned)
    } else {
        None
    }
}

/// Waits for a completed hydration poke. A lone `connected` greeting, a
/// `pokeStart`, or a `pokePart` is intentionally insufficient: clients cannot
/// apply the state until the matching `pokeEnd` arrives.
async fn await_hydration(
    stream: &mut WebSocketStream,
    result: &mut ClientResult,
    setup_timeout: Duration,
) -> Result<String, String> {
    let started = Instant::now();
    let deadline = started + setup_timeout;
    loop {
        let remaining = deadline
            .checked_duration_since(Instant::now())
            .ok_or_else(|| "hydration timeout".to_string())?;
        match tokio::time::timeout(remaining, stream.next()).await {
            Ok(Some(Ok(Message::Text(text)))) => {
                result.frames += 1;
                if let Some(cookie) = poke_end_cookie(&text) {
                    result.hydrated = true;
                    result.hydration_ms = Some(started.elapsed().as_secs_f64() * 1000.0);
                    return Ok(cookie);
                }
            }
            Ok(Some(Ok(Message::Close(_)))) | Ok(None) => {
                return Err("closed during hydration".into())
            }
            Ok(Some(Ok(_))) => {}
            Ok(Some(Err(error))) => {
                return Err(format!(
                    "hydration receive: {}",
                    classify(&error.to_string())
                ))
            }
            Err(_) => return Err("hydration timeout".into()),
        }
    }
}

async fn sustain_pings(
    sink: &mut WebSocketSink,
    stream: &mut WebSocketStream,
    result: &mut ClientResult,
    ping_interval: Duration,
    deadline: Instant,
    workload: Workload,
) -> Result<(), String> {
    while Instant::now() < deadline {
        let ping_at = Instant::now();
        sink.send(Message::text(r#"["ping",{}]"#))
            .await
            .map_err(|_| "ping send".to_string())?;

        // Read until the pong (count any interim frames, including the live
        // fan-out pokes emitted after initial hydration).
        let mut got_pong = false;
        while !got_pong {
            match tokio::time::timeout(Duration::from_secs(5), stream.next()).await {
                Ok(Some(Ok(Message::Text(text)))) => {
                    result.frames += 1;
                    if workload == Workload::Fanout
                        && text_tag(&text).as_deref() == Some("pokeStart")
                    {
                        result.fanout_pokes += 1;
                    }
                    if text == r#"["pong",{}]"# {
                        result
                            .ping_rtts
                            .push(ping_at.elapsed().as_secs_f64() * 1000.0);
                        got_pong = true;
                    }
                }
                Ok(Some(Ok(Message::Close(_)))) | Ok(None) => return Err("closed".into()),
                Ok(Some(Ok(_))) => {}
                Ok(Some(Err(error))) => {
                    return Err(format!("recv: {}", classify(&error.to_string())))
                }
                Err(_) => return Err("pong timeout".into()),
            }
        }
        tokio::time::sleep(ping_interval).await;
    }
    Ok(())
}

/// Runs a single client session. Setup time is measured independently; every
/// successfully initialized client then receives the full sustain duration.
/// `i` selects a stable group/client identity, enabling reconnect mode to use
/// the cookie from its first completed hydration.
async fn client_session(
    base: String,
    i: usize,
    start_delay: Duration,
    ping_interval: Duration,
    duration: Duration,
    setup_timeout: Duration,
    workload: Workload,
    desired_query_patch: String,
    client_schema: String,
    fanout_min_pokes: u64,
) -> ClientResult {
    let mut r = ClientResult::default();
    if !start_delay.is_zero() {
        tokio::time::sleep(start_delay).await;
    }
    let group_id = format!("lt-g{i}");
    let client_id = format!("lt-c{i}");
    let (ws, connect_ms) = match dial(
        &base,
        &group_id,
        &client_id,
        &format!("{i}-initial"),
        None,
        setup_timeout,
    )
    .await
    {
        Ok(connection) => connection,
        Err(error) => {
            r.error = Some(error);
            return r;
        }
    };
    r.connect_ms = connect_ms;
    r.connected = true;
    let (mut sink, mut stream) = ws.split();

    if let Err(error) = consume_greeting(&mut stream, &mut r, setup_timeout).await {
        r.error = Some(error);
        return r;
    }

    let desired = if workload.needs_hydration() {
        desired_query_patch.as_str()
    } else {
        "[]"
    };
    if sink
        .send(Message::text(init_message(desired, Some(&client_schema))))
        .await
        .is_err()
    {
        r.error = Some("init send".into());
        return r;
    }

    if workload.needs_hydration() {
        let cookie = match await_hydration(&mut stream, &mut r, setup_timeout).await {
            Ok(cookie) => cookie,
            Err(error) => {
                r.error = Some(error);
                return r;
            }
        };

        if workload == Workload::Reconnect {
            let _ = sink.send(Message::Close(None)).await;
            drop(sink);
            drop(stream);

            let (ws, reconnect_ms) = match dial(
                &base,
                &group_id,
                &client_id,
                &format!("{i}-reconnect"),
                Some(&cookie),
                setup_timeout,
            )
            .await
            {
                Ok(connection) => connection,
                Err(error) => {
                    r.error = Some(error);
                    return r;
                }
            };
            r.reconnected = true;
            r.reconnect_ms = Some(reconnect_ms);
            let (next_sink, next_stream) = ws.split();
            sink = next_sink;
            stream = next_stream;
            if let Err(error) = consume_greeting(&mut stream, &mut r, setup_timeout).await {
                r.error = Some(error);
                return r;
            }
            // A reconnect has a nonempty baseCookie and reuses the group state,
            // so the initial clientSchema must remain omitted.
            if sink
                .send(Message::text(init_message("[]", None)))
                .await
                .is_err()
            {
                r.error = Some("reconnect init send".into());
                return r;
            }
        }
    }

    // The sustain window starts only after this client has completed all
    // required setup. In ping mode the first pong also proves the server
    // processed initConnection before the client is counted as successful.
    let deadline = Instant::now() + duration;
    if let Err(error) = sustain_pings(
        &mut sink,
        &mut stream,
        &mut r,
        ping_interval,
        deadline,
        workload,
    )
    .await
    {
        r.error = Some(error);
    }
    if workload == Workload::Fanout && r.error.is_none() && r.fanout_pokes < fanout_min_pokes {
        r.error = Some(format!(
            "fanout pokes {} below required {}",
            r.fanout_pokes, fanout_min_pokes
        ));
    }
    r
}

/// Collapses noisy error strings into a small set of reasons.
fn classify(e: &str) -> String {
    let e = e.to_lowercase();
    if e.contains("too many open files") {
        "fd limit (raise ulimit -n)".into()
    } else if e.contains("connection refused") {
        "connection refused".into()
    } else if e.contains("reset") {
        "connection reset".into()
    } else if e.contains("timed out") || e.contains("timeout") {
        "timeout".into()
    } else {
        e.chars().take(40).collect()
    }
}

/// Background sampler: polls `docker stats` for `container` until `stop` is set;
/// returns the folded resource stats.
async fn sample_resources(container: String, stop: Arc<AtomicBool>) -> Option<ResourceStats> {
    let samples = Arc::new(Mutex::new(Vec::<(f64, f64)>::new()));
    while !stop.load(Ordering::SeqCst) {
        if let Ok(out) = tokio::process::Command::new("docker")
            .args([
                "stats",
                "--no-stream",
                "--format",
                "{{.CPUPerc}}|{{.MemUsage}}",
                &container,
            ])
            .output()
            .await
        {
            let line = String::from_utf8_lossy(&out.stdout);
            if let Some((cpu, mem)) = line.trim().split_once('|') {
                if let (Some(c), Some(m)) = (
                    zero_loadtest::parse_cpu_pct(cpu),
                    zero_loadtest::parse_mem_mib(mem),
                ) {
                    samples.lock().unwrap().push((c, m));
                }
            }
        }
        tokio::time::sleep(Duration::from_secs(1)).await;
    }
    let s = samples.lock().unwrap();
    resource_stats(&s)
}

/// Runs the whole load against one target and builds its report.
async fn run_target(url: &str, container: Option<&str>, cfg: &Config) -> RunReport {
    let mut report = RunReport {
        target: url.to_string(),
        workload: cfg.workload.name().to_string(),
        clients: cfg.clients,
        sustain_duration_s: cfg.duration.as_secs_f64(),
        ..Default::default()
    };

    // Resource sampler (docker).
    let stop = Arc::new(AtomicBool::new(false));
    let sampler = container.map(|c| {
        let c = c.to_string();
        let stop = stop.clone();
        tokio::spawn(async move { sample_resources(c, stop).await })
    });

    let run_start = Instant::now();
    let mut tasks = Vec::with_capacity(cfg.clients);
    for i in 0..cfg.clients {
        let start_delay = if cfg.burst {
            Duration::ZERO
        } else {
            // Spread connects across the ramp window.
            Duration::from_secs_f64(
                cfg.ramp.as_secs_f64() * (i as f64) / (cfg.clients.max(1) as f64),
            )
        };
        let base = base_origin(url);
        let pi = cfg.ping_interval;
        let duration = cfg.duration;
        let setup_timeout = cfg.setup_timeout;
        let workload = cfg.workload;
        let query_patch = cfg.desired_query_patch.clone();
        let client_schema = cfg.client_schema.clone();
        let fanout_min_pokes = cfg.fanout_min_pokes;
        tasks.push(tokio::spawn(client_session(
            base,
            i,
            start_delay,
            pi,
            duration,
            setup_timeout,
            workload,
            query_patch,
            client_schema,
            fanout_min_pokes,
        )));
    }

    for t in tasks {
        match t.await {
            Ok(res) => {
                if res.connected {
                    report.connect.record(res.connect_ms);
                }
                if res.connected && res.error.is_none() && !res.ping_rtts.is_empty() {
                    report.connected_ok += 1;
                }
                if res.hydrated {
                    report.hydrated_ok += 1;
                }
                if let Some(hydration_ms) = res.hydration_ms {
                    report.hydration.record(hydration_ms);
                }
                if res.reconnected {
                    report.reconnected_ok += 1;
                }
                if let Some(reconnect_ms) = res.reconnect_ms {
                    report.reconnect.record(reconnect_ms);
                }
                for rtt in res.ping_rtts {
                    report.ping_rtt.record(rtt);
                }
                report.fanout_pokes += res.fanout_pokes;
                report.frames_received += res.frames;
                if let Some(e) = res.error {
                    report.error(e);
                }
            }
            Err(_) => report.error("client task panicked"),
        }
    }
    report.duration_s = run_start.elapsed().as_secs_f64();

    if let Some(sampler) = sampler {
        stop.store(true, Ordering::SeqCst);
        report.resource = sampler.await.ok().flatten();
    }
    report
}

#[tokio::main]
async fn main() {
    let cfg = parse_config();
    eprintln!(
        "zero-loadtest: {} workload, {} clients, {}s sustained per client (ramp {}s, setup timeout {}s), ping every {}ms{}",
        cfg.workload.name(),
        cfg.clients,
        cfg.duration.as_secs(),
        cfg.ramp.as_secs(),
        cfg.setup_timeout.as_secs(),
        cfg.ping_interval.as_millis(),
        if cfg.burst { ", BURST" } else { "" }
    );

    let primary = run_target(&cfg.url, cfg.container.as_deref(), &cfg).await;
    println!("\n{}", render_report(&primary));

    let mut reference_failed = false;
    if cfg.compare {
        if let Some(ref_url) = &cfg.ref_url {
            eprintln!("comparing against reference {ref_url}…");
            let reference = run_target(ref_url, cfg.ref_container.as_deref(), &cfg).await;
            reference_failed = report_failed(&reference, cfg.workload);
            println!("{}", render_report(&reference));
            println!("{}", render_comparison(&primary, &reference));
        } else {
            eprintln!("--compare set but no --ref-url / LOAD_REF_URL");
        }
    }

    // Non-zero exit if the target did not sustain the requested shape. A
    // hydration/reconnect run must prove data-path completion; a fan-out run
    // additionally enforces the requested external-write observation count.
    if report_failed(&primary, cfg.workload) || reference_failed {
        eprintln!(
            "WARNING: benchmark target failed to sustain the workload (primary success {:.1}%)",
            primary.success_rate() * 100.0,
        );
        std::process::exit(1);
    }
}

fn report_failed(report: &RunReport, workload: Workload) -> bool {
    if report.success_rate() < 0.95 {
        return true;
    }
    match workload {
        Workload::Ping => report.ping_rtt.is_empty(),
        Workload::Hydrate | Workload::Fanout => report.hydrated_ok < report.clients,
        Workload::Reconnect => {
            report.hydrated_ok < report.clients || report.reconnected_ok < report.clients
        }
    }
}

/// A compact side-by-side table for the two targets.
fn render_comparison(a: &RunReport, b: &RunReport) -> String {
    let (pa, pb) = (a.ping_rtt.summary(), b.ping_rtt.summary());
    let (ha, hb) = (a.hydration.summary(), b.hydration.summary());
    let (ra, rb) = (a.reconnect.summary(), b.reconnect.summary());
    let mut out = String::from("── comparison (A=primary  B=reference) ──\n");
    let row = |label: &str, av: String, bv: String| format!("  {label:<22} A {av:<14} B {bv}\n");
    out.push_str(&row(
        "connected",
        format!("{:.1}%", a.success_rate() * 100.0),
        format!("{:.1}%", b.success_rate() * 100.0),
    ));
    out.push_str(&row(
        "ping p50/p99 ms",
        format!("{:.2}/{:.2}", pa.p50, pa.p99),
        format!("{:.2}/{:.2}", pb.p50, pb.p99),
    ));
    out.push_str(&row(
        "sustain ping/s",
        format!("{:.0}", a.throughput_ops_s()),
        format!("{:.0}", b.throughput_ops_s()),
    ));
    if !a.hydration.is_empty() || !b.hydration.is_empty() {
        out.push_str(&row(
            "hydrate p50/p99 ms",
            format!(
                "{:.1}/{:.1} ({}/{})",
                ha.p50, ha.p99, a.hydrated_ok, a.clients
            ),
            format!(
                "{:.1}/{:.1} ({}/{})",
                hb.p50, hb.p99, b.hydrated_ok, b.clients
            ),
        ));
    }
    if !a.reconnect.is_empty() || !b.reconnect.is_empty() {
        out.push_str(&row(
            "reconnect p50/p99 ms",
            format!(
                "{:.1}/{:.1} ({}/{})",
                ra.p50, ra.p99, a.reconnected_ok, a.clients
            ),
            format!(
                "{:.1}/{:.1} ({}/{})",
                rb.p50, rb.p99, b.reconnected_ok, b.clients
            ),
        ));
    }
    if a.fanout_pokes > 0 || b.fanout_pokes > 0 {
        out.push_str(&row(
            "fan-out pokes",
            a.fanout_pokes.to_string(),
            b.fanout_pokes.to_string(),
        ));
    }
    if let (Some(ra), Some(rb)) = (&a.resource, &b.resource) {
        out.push_str(&row(
            "CPU peak %",
            format!("{:.0}", ra.peak_cpu_pct),
            format!("{:.0}", rb.peak_cpu_pct),
        ));
        out.push_str(&row(
            "mem peak MiB",
            format!("{:.0}", ra.peak_mem_mib),
            format!("{:.0}", rb.peak_mem_mib),
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn workload_parser_rejects_an_unknown_shape() {
        assert_eq!(Workload::parse("hydrate"), Ok(Workload::Hydrate));
        assert_eq!(Workload::parse("reconnect"), Ok(Workload::Reconnect));
        assert!(Workload::parse("idle").is_err());
    }

    #[test]
    fn data_path_init_is_nonempty_and_declares_schema() {
        let message = init_message(DEFAULT_QUERY_PATCH, Some(DEFAULT_CLIENT_SCHEMA));
        assert!(message.contains("loadtest-issue-all"));
        assert!(message.contains("clientSchema"));
        assert!(message.contains("desiredQueriesPatch"));
    }

    #[test]
    fn reconnect_url_preserves_and_escapes_the_cookie() {
        let url = connect_url(
            "ws://localhost:4848",
            "group one",
            "client",
            "ws",
            Some("00:01/with space"),
        );
        assert!(url.starts_with("ws://localhost:4848/sync/v51/connect?"));
        assert!(url.contains("clientGroupID=group%20one"));
        assert!(url.contains("baseCookie=00%3A01%2Fwith%20space"));
    }

    #[test]
    fn poke_end_cookie_requires_the_correct_message_kind() {
        assert_eq!(
            poke_end_cookie(r#"["pokeEnd",{"cookie":"00:01"}]"#),
            Some("00:01".to_string())
        );
        assert_eq!(poke_end_cookie(r#"["pokeStart",{"cookie":"00:01"}]"#), None);
    }
}
